### ISSUE TITLE
Change the section  naming conventions in the ALFA report

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/multiqc-plugins#31]
**Is your feature request related to a problem? Please describe.**
I would like the title of the sections of the alfa in the multiqc report to be more meaningful. 

**Describe the solution you'd like**
Replace some specific ALFA names with more descriptive ones. In particular the UniqueMultiple with MultimappersIncluded as the UniqueMultiple is confusing and the Unique with UniqueMappers.

**Comment by AngryMaciek** [comment]
More info in the discussion here: https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/164

**Comment by AngryMaciek** [comment]
Titles in the output report are just as meaningful as the input data provided by the user: directory names are parsed and become sub-section headers. The fact that some user/pipeline provides nasty names (in the case of _zarp_ : propagated from _STAR_ through _ALFA_ up to here) is not really an issue with this codebase...
