### ISSUE TITLE
TIN score plugin

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/multiqc-plugins#6]
**Is your feature request related to a problem? Please describe.**
We would like to have one plugin related to creating boxplots of TIN scores.

**Describe the solution you'd like**
A plugin structured the same as `ALFA` plugin.

**Additional context**
Use your previous work on parsing TIN scores.

**Comment by AngryMaciek** [comment]
Last time I checked *boxplots* were not supported in *MultiQC*.
In that case we would have to plot full distributions of TIN scores per sample.

Example plot of that type from the `MultiQC docs`:

![qualimap_coverage_histogram](https://user-images.githubusercontent.com/19755308/96985993-4c1cec00-1521-11eb-9bfd-49a328435ff6.png)

**Comment by AngryMaciek** [comment]
I think that as input we should use per-sample files called `TIN_score.tsv`, located in sample-separate subdirectories inside the test directory. Forget the merged TSV table.

**Comment by krish8484** [comment]
For each sample, what will we be having on the x-axis and the y-axis? In each tsv file there are multiple transcripts, how will that come into the picture?

**Comment by AngryMaciek** [comment]
These files contain only one information: per-transcript TIN score. I just want distribution of those, so x-axis would be "TIN score", y-axis would be "Counts" (or Density, if it is supported, I did not check what are the options for these plots). It is just like on a histogram.
